apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: stockyard
    release: {{ .Release.Name }}
type: Opaque
stringData:
  {{- if .Values.secrets.adminKey }}
  STOCKYARD_ADMIN_KEY: {{ .Values.secrets.adminKey | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.googleApiKey }}
  GOOGLE_API_KEY: {{ .Values.secrets.googleApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.groqApiKey }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.resendApiKey }}
  RESEND_API_KEY: {{ .Values.secrets.resendApiKey | quote }}
  {{- end }}
