FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/crucible ./cmd/crucible/

FROM alpine:3.19
COPY --from=build /bin/crucible /usr/local/bin/crucible
EXPOSE 9706
CMD ["crucible"]
