FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/fossilrec ./cmd/fossilrec/

FROM alpine:3.19
COPY --from=build /bin/fossilrec /usr/local/bin/fossilrec
EXPOSE 9702
CMD ["fossilrec"]
