FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/spore ./cmd/spore/

FROM alpine:3.19
COPY --from=build /bin/spore /usr/local/bin/spore
EXPOSE 9709
CMD ["spore"]
