// Package heal applies validated patches to the actual codebase, creating git
// branches and running tests to verify the fix before presenting it for merge.
package heal

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/stockyard-dev/stockyard/internal/fault/diagnose"
	"github.com/stockyard-dev/stockyard/internal/fault/sandbox"
	"github.com/stockyard-dev/stockyard/internal/fault/store"
)

// HealResult describes the outcome of applying a patch to the real codebase.
type HealResult struct {
	BranchName   string   `json:"branch_name"`
	FilesChanged []string `json:"files_changed"`
	TestsPassed  bool     `json:"tests_passed"`
	TestOutput   string   `json:"test_output"`
	Error        string   `json:"error,omitempty"`
	AppliedAt    time.Time `json:"applied_at"`
}

// Healer manages patch application against a target directory.
type Healer struct {
	targetDir string
	store     *store.DB
}

// New creates a Healer targeting the given directory.
func New(targetDir string, db *store.DB) *Healer {
	return &Healer{targetDir: targetDir, store: db}
}

// Apply validates a diagnosis patch in sandbox, then applies it to the real
// codebase on a new git branch, runs tests, and records the attempt.
func (h *Healer) Apply(ctx context.Context, fingerprint string, diag diagnose.Diagnosis) (*HealResult, error) {
	result := &HealResult{AppliedAt: time.Now()}

	if diag.Patch == nil {
		return nil, fmt.Errorf("diagnosis has no patch to apply")
	}

	// 1. Sandbox validation first
	testResult, err := sandbox.Test(ctx, diag.Patch, h.targetDir)
	if err != nil {
		result.Error = fmt.Sprintf("sandbox validation failed: %v", err)
		h.saveAttempt(fingerprint, result)
		return result, fmt.Errorf("sandbox validation failed: %w", err)
	}
	if !testResult.Passed {
		result.Error = fmt.Sprintf("sandbox tests failed: %s", testResult.Error)
		result.TestOutput = testResult.Output
		h.saveAttempt(fingerprint, result)
		return result, fmt.Errorf("sandbox tests failed: %s", testResult.Error)
	}

	// 2. Create a fix branch
	branchName := fmt.Sprintf("fault/fix-%s", sanitizeBranch(fingerprint))
	result.BranchName = branchName

	if err := gitCmd(ctx, h.targetDir, "checkout", "-b", branchName); err != nil {
		result.Error = fmt.Sprintf("git branch creation failed: %v", err)
		h.saveAttempt(fingerprint, result)
		return result, fmt.Errorf("creating branch: %w", err)
	}

	// 3. Apply the patch to the real file
	patchFile := filepath.Join(h.targetDir, diag.Patch.File)
	content, err := os.ReadFile(patchFile)
	if err != nil {
		result.Error = fmt.Sprintf("reading target file: %v", err)
		h.rollbackBranch(ctx, branchName)
		h.saveAttempt(fingerprint, result)
		return result, fmt.Errorf("reading %s: %w", diag.Patch.File, err)
	}

	patched := strings.Replace(string(content), diag.Patch.Before, diag.Patch.After, 1)
	if patched == string(content) {
		result.Error = "patch target text not found in file"
		h.rollbackBranch(ctx, branchName)
		h.saveAttempt(fingerprint, result)
		return result, fmt.Errorf("patch before-text not found in %s", diag.Patch.File)
	}

	if err := os.WriteFile(patchFile, []byte(patched), 0644); err != nil {
		result.Error = err.Error()
		h.rollbackBranch(ctx, branchName)
		h.saveAttempt(fingerprint, result)
		return result, err
	}

	result.FilesChanged = []string{diag.Patch.File}

	// 4. Run tests on the real codebase
	testOutput, testErr := runTests(ctx, h.targetDir, diag.Patch.Language)
	result.TestOutput = testOutput
	if testErr != nil {
		result.TestsPassed = false
		result.Error = fmt.Sprintf("tests failed after patch: %v", testErr)
		// Revert the file but keep the branch for inspection
		_ = os.WriteFile(patchFile, content, 0644)
		h.saveAttempt(fingerprint, result)
		return result, fmt.Errorf("tests failed: %w", testErr)
	}
	result.TestsPassed = true

	// 5. Git commit the fix
	_ = gitCmd(ctx, h.targetDir, "add", diag.Patch.File)
	commitMsg := fmt.Sprintf("fix(%s): %s\n\nAuto-generated by Stockyard Fault.\nFingerprint: %s",
		filepath.Base(diag.Patch.File), diag.Patch.Description, fingerprint)
	_ = gitCmd(ctx, h.targetDir, "commit", "-m", commitMsg)

	h.saveAttempt(fingerprint, result)
	return result, nil
}

func (h *Healer) saveAttempt(fingerprint string, result *HealResult) {
	if h.store == nil {
		return
	}
	_ = h.store.SaveHealAttempt(store.HealAttempt{
		ErrorFingerprint: fingerprint,
		BranchName:       result.BranchName,
		FilesChanged:     strings.Join(result.FilesChanged, ","),
		TestsPassed:      result.TestsPassed,
		TestOutput:       result.TestOutput,
		CreatedAt:        result.AppliedAt,
	})
}

func (h *Healer) rollbackBranch(ctx context.Context, branch string) {
	_ = gitCmd(ctx, h.targetDir, "checkout", "-")
	_ = gitCmd(ctx, h.targetDir, "branch", "-D", branch)
}

func gitCmd(ctx context.Context, dir string, args ...string) error {
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("git %s: %s: %w", strings.Join(args, " "), string(out), err)
	}
	return nil
}

func runTests(ctx context.Context, dir, language string) (string, error) {
	var cmd *exec.Cmd
	switch language {
	case "go":
		cmd = exec.CommandContext(ctx, "go", "test", "./...")
	case "python":
		cmd = exec.CommandContext(ctx, "python", "-m", "pytest", "-x")
	case "typescript", "javascript":
		cmd = exec.CommandContext(ctx, "npm", "test")
	default:
		cmd = exec.CommandContext(ctx, "go", "test", "./...")
	}
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return string(out), err
}

func sanitizeBranch(s string) string {
	r := strings.NewReplacer(":", "-", "/", "-", " ", "-")
	name := r.Replace(s)
	if len(name) > 50 {
		name = name[:50]
	}
	return name
}
