// Package testgen generates runnable test code from spec acceptance criteria.
//
// Tests are the bridge between the human-readable spec and the machine-verifiable
// implementation. The spec says what should happen; tests verify that it does.
// Tests are generated once from the spec and re-run against each code generation
// iteration until all pass.
package testgen

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/stockyard-dev/stockyard/internal/iron/parser"
)

// GeneratedTest holds a single generated test case.
type GeneratedTest struct {
	Name        string `json:"name"`         // Test function name
	Feature     string `json:"feature"`      // Parent feature name
	Behavior    string `json:"behavior"`     // Parent behavior name
	Description string `json:"description"`  // Human-readable description
	Code        string `json:"code"`         // Generated test code
}

// GenerateTests produces test code from a spec's acceptance criteria.
func GenerateTests(spec *parser.Spec) ([]GeneratedTest, string) {
	switch spec.Language {
	case "go":
		return generateGoTests(spec)
	case "python":
		return generatePythonTests(spec)
	case "typescript":
		return generateTypeScriptTests(spec)
	default:
		return generateGoTests(spec)
	}
}

// generateGoTests produces Go test functions.
func generateGoTests(spec *parser.Spec) ([]GeneratedTest, string) {
	var tests []GeneratedTest
	var sb strings.Builder

	sb.WriteString("package main_test\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"bytes\"\n")
	sb.WriteString("\t\"encoding/json\"\n")
	sb.WriteString("\t\"io\"\n")
	sb.WriteString("\t\"net/http\"\n")
	sb.WriteString("\t\"net/http/httptest\"\n")
	sb.WriteString("\t\"strings\"\n")
	sb.WriteString("\t\"testing\"\n")
	sb.WriteString(")\n\n")

	sb.WriteString("// setupServer creates a test server running the generated application.\n")
	sb.WriteString("// This function must be implemented by the code generator.\n")
	sb.WriteString("func setupServer(t *testing.T) *httptest.Server {\n")
	sb.WriteString("\tt.Helper()\n")
	sb.WriteString("\thandler := NewRouter() // generated by codegen\n")
	sb.WriteString("\treturn httptest.NewServer(handler)\n")
	sb.WriteString("}\n\n")

	for _, feature := range spec.Features {
		for _, behavior := range feature.Behaviors {
			for i, acc := range behavior.Acceptance {
				testName := fmt.Sprintf("Test_%s_%s_%d",
					sanitize(feature.Name), sanitize(behavior.Name), i+1)

				testCode := generateGoTestFunc(testName, acc, feature.Name, behavior.Name)

				tests = append(tests, GeneratedTest{
					Name:        testName,
					Feature:     feature.Name,
					Behavior:    behavior.Name,
					Description: acc.Description,
					Code:        testCode,
				})

				sb.WriteString(testCode)
				sb.WriteString("\n")
			}
		}
	}

	return tests, sb.String()
}

func generateGoTestFunc(name string, acc parser.Acceptance, feature, behavior string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("// %s\n", acc.Description))
	sb.WriteString(fmt.Sprintf("// Feature: %s / Behavior: %s\n", feature, behavior))
	sb.WriteString(fmt.Sprintf("func %s(t *testing.T) {\n", name))
	sb.WriteString("\tts := setupServer(t)\n")
	sb.WriteString("\tdefer ts.Close()\n\n")

	// Build request
	method := strings.ToUpper(acc.Method)
	if method == "" {
		method = "GET"
	}
	path := acc.Path
	if path == "" {
		path = "/"
	}

	if acc.Body != nil {
		sb.WriteString("\tbody, _ := json.Marshal(map[string]any{\n")
		for k, v := range acc.Body {
			sb.WriteString(fmt.Sprintf("\t\t%q: %s,\n", k, goLiteral(v)))
		}
		sb.WriteString("\t})\n")
		sb.WriteString(fmt.Sprintf("\treq, err := http.NewRequest(%q, ts.URL+%q, bytes.NewReader(body))\n", method, path))
	} else {
		sb.WriteString(fmt.Sprintf("\treq, err := http.NewRequest(%q, ts.URL+%q, nil)\n", method, path))
	}

	sb.WriteString("\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n")

	if acc.Body != nil {
		sb.WriteString("\treq.Header.Set(\"Content-Type\", \"application/json\")\n")
	}
	for k, v := range acc.Headers {
		sb.WriteString(fmt.Sprintf("\treq.Header.Set(%q, %q)\n", k, v))
	}

	sb.WriteString("\n\tresp, err := http.DefaultClient.Do(req)\n")
	sb.WriteString("\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n")
	sb.WriteString("\tdefer resp.Body.Close()\n")
	sb.WriteString("\trespBody, _ := io.ReadAll(resp.Body)\n\n")

	// Assertions
	if acc.Expect.Status > 0 {
		sb.WriteString(fmt.Sprintf("\tif resp.StatusCode != %d {\n", acc.Expect.Status))
		sb.WriteString(fmt.Sprintf("\t\tt.Errorf(\"expected status %d, got %%d: %%s\", resp.StatusCode, string(respBody))\n", acc.Expect.Status))
		sb.WriteString("\t}\n")
	}

	for k, v := range acc.Expect.Headers {
		sb.WriteString(fmt.Sprintf("\tif got := resp.Header.Get(%q); got != %q {\n", k, v))
		sb.WriteString(fmt.Sprintf("\t\tt.Errorf(\"expected header %s=%q, got %%q\", got)\n", k, v))
		sb.WriteString("\t}\n")
	}

	for _, s := range acc.Expect.Contains {
		sb.WriteString(fmt.Sprintf("\tif !strings.Contains(string(respBody), %q) {\n", s))
		sb.WriteString(fmt.Sprintf("\t\tt.Errorf(\"response should contain %q, got: %%s\", string(respBody))\n", s))
		sb.WriteString("\t}\n")
	}

	for _, s := range acc.Expect.NotContains {
		sb.WriteString(fmt.Sprintf("\tif strings.Contains(string(respBody), %q) {\n", s))
		sb.WriteString(fmt.Sprintf("\t\tt.Errorf(\"response should NOT contain %q, got: %%s\", string(respBody))\n", s))
		sb.WriteString("\t}\n")
	}

	if acc.Expect.Body != nil {
		sb.WriteString("\tvar result map[string]any\n")
		sb.WriteString("\tif err := json.Unmarshal(respBody, &result); err != nil {\n")
		sb.WriteString("\t\tt.Fatalf(\"response is not valid JSON: %v\", err)\n")
		sb.WriteString("\t}\n")

		for k, v := range acc.Expect.Body {
			sb.WriteString(fmt.Sprintf("\tif result[%q] != %s {\n", k, goLiteral(v)))
			sb.WriteString(fmt.Sprintf("\t\tt.Errorf(\"expected %s=%%v, got %%v\", %s, result[%q])\n", k, goLiteral(v), k))
			sb.WriteString("\t}\n")
		}
	}

	// Suppress unused variable warnings
	sb.WriteString("\t_ = respBody\n")
	sb.WriteString("}\n")

	return sb.String()
}

// generatePythonTests produces pytest test functions.
func generatePythonTests(spec *parser.Spec) ([]GeneratedTest, string) {
	var tests []GeneratedTest
	var sb strings.Builder

	sb.WriteString("import pytest\n")
	sb.WriteString("import requests\n")
	sb.WriteString("import json\n\n")
	sb.WriteString("BASE_URL = \"http://localhost:8080\"  # Set by test runner\n\n")

	for _, feature := range spec.Features {
		for _, behavior := range feature.Behaviors {
			for i, acc := range behavior.Acceptance {
				testName := fmt.Sprintf("test_%s_%s_%d",
					sanitize_lower(feature.Name), sanitize_lower(behavior.Name), i+1)

				testCode := generatePythonTestFunc(testName, acc)

				tests = append(tests, GeneratedTest{
					Name:        testName,
					Feature:     feature.Name,
					Behavior:    behavior.Name,
					Description: acc.Description,
					Code:        testCode,
				})

				sb.WriteString(testCode)
				sb.WriteString("\n\n")
			}
		}
	}

	return tests, sb.String()
}

func generatePythonTestFunc(name string, acc parser.Acceptance) string {
	var sb strings.Builder

	method := strings.ToLower(acc.Method)
	if method == "" {
		method = "get"
	}
	path := acc.Path
	if path == "" {
		path = "/"
	}

	sb.WriteString(fmt.Sprintf("def %s():\n", name))
	sb.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n", acc.Description))

	if acc.Body != nil {
		bodyJSON, marshalErr := json.Marshal(acc.Body)
		if marshalErr != nil {
			bodyJSON = []byte("{}")
		}
		sb.WriteString(fmt.Sprintf("    resp = requests.%s(BASE_URL + \"%s\", json=%s)\n", method, path, string(bodyJSON)))
	} else {
		sb.WriteString(fmt.Sprintf("    resp = requests.%s(BASE_URL + \"%s\")\n", method, path))
	}

	if acc.Expect.Status > 0 {
		sb.WriteString(fmt.Sprintf("    assert resp.status_code == %d, f\"Expected %d, got {resp.status_code}: {resp.text}\"\n", acc.Expect.Status, acc.Expect.Status))
	}

	for _, s := range acc.Expect.Contains {
		sb.WriteString(fmt.Sprintf("    assert \"%s\" in resp.text, f\"Response should contain '%s': {resp.text}\"\n", s, s))
	}

	for _, s := range acc.Expect.NotContains {
		sb.WriteString(fmt.Sprintf("    assert \"%s\" not in resp.text, f\"Response should NOT contain '%s': {resp.text}\"\n", s, s))
	}

	if acc.Expect.Body != nil {
		sb.WriteString("    data = resp.json()\n")
		for k, v := range acc.Expect.Body {
			sb.WriteString(fmt.Sprintf("    assert data[\"%s\"] == %s, f\"Expected %s={%s}, got {data.get('%s')}\"\n", k, pythonLiteral(v), k, pythonLiteral(v), k))
		}
	}

	return sb.String()
}

// generateTypeScriptTests produces Jest/Vitest test functions.
func generateTypeScriptTests(spec *parser.Spec) ([]GeneratedTest, string) {
	var tests []GeneratedTest
	var sb strings.Builder

	sb.WriteString("import { describe, it, expect } from 'vitest';\n\n")
	sb.WriteString("const BASE_URL = process.env.TEST_URL || 'http://localhost:8080';\n\n")

	for _, feature := range spec.Features {
		sb.WriteString(fmt.Sprintf("describe('%s', () => {\n", feature.Name))

		for _, behavior := range feature.Behaviors {
			for i, acc := range behavior.Acceptance {
				testName := fmt.Sprintf("%s > %s > %d", feature.Name, behavior.Name, i+1)

				testCode := generateTSTestFunc(acc, behavior.Name)

				tests = append(tests, GeneratedTest{
					Name:        testName,
					Feature:     feature.Name,
					Behavior:    behavior.Name,
					Description: acc.Description,
					Code:        testCode,
				})

				sb.WriteString(testCode)
			}
		}
		sb.WriteString("});\n\n")
	}

	return tests, sb.String()
}

func generateTSTestFunc(acc parser.Acceptance, behaviorName string) string {
	var sb strings.Builder

	method := strings.ToUpper(acc.Method)
	if method == "" {
		method = "GET"
	}
	path := acc.Path
	if path == "" {
		path = "/"
	}

	sb.WriteString(fmt.Sprintf("  it('%s', async () => {\n", acc.Description))

	if acc.Body != nil {
		bodyJSON, marshalErr := json.Marshal(acc.Body)
		if marshalErr != nil {
			bodyJSON = []byte("{}")
		}
		sb.WriteString(fmt.Sprintf("    const resp = await fetch(`${BASE_URL}%s`, {\n", path))
		sb.WriteString(fmt.Sprintf("      method: '%s',\n", method))
		sb.WriteString("      headers: { 'Content-Type': 'application/json' },\n")
		sb.WriteString(fmt.Sprintf("      body: JSON.stringify(%s),\n", string(bodyJSON)))
		sb.WriteString("    });\n")
	} else {
		sb.WriteString(fmt.Sprintf("    const resp = await fetch(`${BASE_URL}%s`, { method: '%s' });\n", path, method))
	}

	if acc.Expect.Status > 0 {
		sb.WriteString(fmt.Sprintf("    expect(resp.status).toBe(%d);\n", acc.Expect.Status))
	}

	if acc.Expect.Contains != nil || acc.Expect.NotContains != nil || acc.Expect.Body != nil {
		sb.WriteString("    const body = await resp.text();\n")
	}

	for _, s := range acc.Expect.Contains {
		sb.WriteString(fmt.Sprintf("    expect(body).toContain('%s');\n", s))
	}

	for _, s := range acc.Expect.NotContains {
		sb.WriteString(fmt.Sprintf("    expect(body).not.toContain('%s');\n", s))
	}

	if acc.Expect.Body != nil {
		sb.WriteString("    const data = JSON.parse(body);\n")
		for k, v := range acc.Expect.Body {
			sb.WriteString(fmt.Sprintf("    expect(data.%s).toBe(%s);\n", k, tsLiteral(v)))
		}
	}

	sb.WriteString("  });\n\n")

	return sb.String()
}

// =========================================================================
// Helpers
// =========================================================================

func sanitize(s string) string {
	s = strings.ReplaceAll(s, " ", "_")
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "_")
	var out []byte
	for _, c := range []byte(s) {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
			out = append(out, c)
		}
	}
	return string(out)
}

func sanitize_lower(s string) string {
	return strings.ToLower(sanitize(s))
}

func goLiteral(v any) string {
	switch val := v.(type) {
	case string:
		return fmt.Sprintf("%q", val)
	case float64:
		if val == float64(int(val)) {
			return fmt.Sprintf("float64(%d)", int(val))
		}
		return fmt.Sprintf("%g", val)
	case int:
		return fmt.Sprintf("float64(%d)", val) // JSON numbers decode as float64
	case bool:
		return fmt.Sprintf("%t", val)
	default:
		return fmt.Sprintf("%v", val)
	}
}

func pythonLiteral(v any) string {
	switch val := v.(type) {
	case string:
		return fmt.Sprintf("\"%s\"", val)
	case float64:
		if val == float64(int(val)) {
			return fmt.Sprintf("%d", int(val))
		}
		return fmt.Sprintf("%g", val)
	case bool:
		if val {
			return "True"
		}
		return "False"
	default:
		return fmt.Sprintf("%v", val)
	}
}

func tsLiteral(v any) string {
	switch val := v.(type) {
	case string:
		return fmt.Sprintf("'%s'", val)
	case float64:
		if val == float64(int(val)) {
			return fmt.Sprintf("%d", int(val))
		}
		return fmt.Sprintf("%g", val)
	case bool:
		return fmt.Sprintf("%t", val)
	default:
		return fmt.Sprintf("%v", val)
	}
}
