// Package apiserver — Cloud backup blob storage.
//
// BlobStore is the interface the Cloud backup handler writes through.
// Implementations:
//   LocalBlobStore  — files under a directory. Used for v0. Swap for
//                     S3 later without changing handler code.
//
// The blob body is the desktop's encrypted backup tarball. The server
// never sees plaintext — that's the point of the e2e-encrypted
// "Cloud is a replica, not a source of truth" design in ROADMAP.md §6.
// We store what we're given and give it back on demand.
package apiserver

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// BlobStore persists opaque bytes keyed by an opaque string. Keys are
// generated by the Cloud handler (see cloud_handlers.go) and stored in
// cloud_backup_blobs.blob_key. Implementations must treat keys as
// untrusted and reject anything that might escape their namespace.
type BlobStore interface {
	// Put stores reader's bytes under key. Returns number of bytes
	// written and any error. Overwrites are allowed (idempotent
	// retries from the desktop client).
	Put(key string, r io.Reader) (int64, error)

	// Get returns a reader for the bytes stored under key, or an
	// error if the key doesn't exist.
	Get(key string) (io.ReadCloser, error)

	// Delete removes the bytes. No error if the key doesn't exist.
	Delete(key string) error
}

// ErrBlobNotFound is returned by Get when the key has no bytes.
var ErrBlobNotFound = errors.New("blob not found")

// LocalBlobStore stores blobs as files under a root directory. One
// file per blob_key. Keys must be POSIX-safe (no slashes, no null
// bytes, length < 255) — enforced at Put time.
type LocalBlobStore struct {
	root string
}

// NewLocalBlobStore ensures the root exists and returns a store.
// Safe to call with the same root from multiple processes; each
// Put is a simple file write.
func NewLocalBlobStore(root string) (*LocalBlobStore, error) {
	if root == "" {
		return nil, errors.New("empty blob store root")
	}
	if err := os.MkdirAll(root, 0o755); err != nil {
		return nil, fmt.Errorf("mkdir blob root %s: %w", root, err)
	}
	return &LocalBlobStore{root: root}, nil
}

// safeKey rejects anything that could walk the filesystem. Callers
// should use server-generated keys (random UUIDs / account+timestamp
// hashes) that by construction pass this check.
func safeKey(key string) error {
	if key == "" {
		return errors.New("empty key")
	}
	if len(key) > 255 {
		return errors.New("key too long")
	}
	if strings.ContainsAny(key, "/\\\x00") {
		return errors.New("key contains illegal chars")
	}
	if key == "." || key == ".." {
		return errors.New("key is reserved")
	}
	return nil
}

// Put writes the blob to disk. Uses a tmp-then-rename pattern so a
// crash mid-write doesn't leave a half-file visible under its final
// name. The final file is then fsync'd.
func (s *LocalBlobStore) Put(key string, r io.Reader) (int64, error) {
	if err := safeKey(key); err != nil {
		return 0, err
	}
	final := filepath.Join(s.root, key)
	tmp, err := os.CreateTemp(s.root, "blob-*.tmp")
	if err != nil {
		return 0, fmt.Errorf("temp file: %w", err)
	}
	tmpName := tmp.Name()
	// Best-effort cleanup if something goes wrong mid-function.
	defer func() {
		if _, err := os.Stat(tmpName); err == nil {
			os.Remove(tmpName)
		}
	}()

	n, err := io.Copy(tmp, r)
	if err != nil {
		tmp.Close()
		return n, fmt.Errorf("write blob: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return n, fmt.Errorf("fsync blob: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return n, fmt.Errorf("close blob: %w", err)
	}
	if err := os.Rename(tmpName, final); err != nil {
		return n, fmt.Errorf("rename blob: %w", err)
	}
	return n, nil
}

// Get opens the blob file for reading.
func (s *LocalBlobStore) Get(key string) (io.ReadCloser, error) {
	if err := safeKey(key); err != nil {
		return nil, err
	}
	f, err := os.Open(filepath.Join(s.root, key))
	if os.IsNotExist(err) {
		return nil, ErrBlobNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("open blob: %w", err)
	}
	return f, nil
}

// Delete removes the file. Absent files are not an error.
func (s *LocalBlobStore) Delete(key string) error {
	if err := safeKey(key); err != nil {
		return err
	}
	err := os.Remove(filepath.Join(s.root, key))
	if os.IsNotExist(err) {
		return nil
	}
	return err
}
