package site

import "strings"

// quickMatch maps common normalized inputs to pre-cached bundle slugs.
// These slugs reference entries in the recommendation_cache table.
// Add to this map when a normalized input gets 10+ cache hits.
var quickMatch = map[string]string{
	// Healthcare
	"therapist":          "therapist",
	"therapy":            "therapist",
	"counselor":          "therapist",
	"counseling":         "therapist",
	"psychologist":       "therapist",
	"psychotherapy":      "therapist",
	"mental health":      "therapist",
	"private practice":   "therapist",
	"lcsw":               "therapist",
	"lmft":               "therapist",
	"dentist":            "dental",
	"dental practice":    "dental",
	"dental office":      "dental",
	"dental clinic":      "dental",
	"vet":                "veterinary",
	"veterinary":         "veterinary",
	"veterinarian":       "veterinary",
	"vet clinic":         "veterinary",
	"animal clinic":      "veterinary",
	"chiropractor":       "chiropractor",
	"chiropractic":       "chiropractor",
	"physical therapy":   "physical-therapy",
	"physical therapist": "physical-therapy",
	"pt clinic":          "physical-therapy",
	"optometrist":        "optometry",
	"optometry":          "optometry",
	"eye doctor":         "optometry",
	"acupuncture":        "acupuncture",
	"acupuncturist":      "acupuncture",
	"speech therapist":   "speech-therapist",
	"speech pathologist": "speech-therapist",
	"slp":                "speech-therapist",
	"nutritionist":       "nutritionist",
	"dietitian":          "nutritionist",
	"doula":              "doula-midwife",
	"midwife":            "doula-midwife",

	// Small Business
	"barber":           "barber-salon",
	"barber shop":      "barber-salon",
	"barbershop":       "barber-salon",
	"hair salon":       "barber-salon",
	"hairstylist":      "barber-salon",
	"salon":            "barber-salon",
	"restaurant":       "restaurant",
	"cafe":             "restaurant",
	"coffee shop":      "restaurant",
	"diner":            "restaurant",
	"food truck":       "food-truck",
	"freelancer":       "freelancer",
	"freelance":        "freelancer",
	"consultant":       "freelancer",
	"contractor":       "freelancer",
	"auto shop":        "auto-shop",
	"auto repair":      "auto-shop",
	"mechanic":         "auto-shop",
	"body shop":        "auto-shop",
	"lawn care":        "lawn-care",
	"landscaping":      "lawn-care",
	"landscaper":       "lawn-care",
	"mowing":           "lawn-care",
	"cleaning service": "cleaning-service",
	"cleaning business": "cleaning-service",
	"maid service":      "cleaning-service",
	"house cleaning":    "cleaning-service",
	"janitor":           "cleaning-service",
	"janitorial":        "cleaning-service",
	"tattoo":            "tattoo",
	"tattoo shop":       "tattoo",
	"tattoo studio":     "tattoo",
	"tattoo artist":     "tattoo",
	"piercing":          "tattoo",
	"florist":           "florist",
	"flower shop":       "florist",
	"plumber":           "trades",
	"plumbing":          "trades",
	"electrician":       "trades",
	"electrical":        "trades",
	"hvac":              "trades",
	"handyman":          "trades",
	"dog groomer":       "pet-services",
	"dog grooming":      "pet-services",
	"pet grooming":      "pet-services",
	"pet sitter":        "pet-services",
	"pet sitting":       "pet-services",
	"dog walker":        "pet-services",
	"etsy":              "etsy",
	"etsy shop":         "etsy",
	"etsy seller":       "etsy",
	"handmade":          "etsy",
	"craft business":    "etsy",
	"catering":          "catering",
	"caterer":           "catering",
	"moving company":    "moving-company",
	"movers":            "moving-company",
	"tutor":             "tutoring",
	"tutoring":          "tutoring",
	"print shop":        "print-shop",
	"sign shop":         "print-shop",
	"event planner":     "event-planner",
	"event planning":    "event-planner",
	"interior designer": "interior-designer",
	"interior design":   "interior-designer",
	"bookkeeper":        "bookkeeper",
	"bookkeeping":       "bookkeeper",
	"accountant":        "accountant-tax",
	"tax preparer":      "accountant-tax",
	"cpa":               "accountant-tax",
	"accounting":        "accountant-tax",
	"accounting firm":   "accountant-tax",

	// Professional Services
	"photographer":         "photography",
	"photography":          "photography",
	"wedding photographer": "photography",
	"wedding planner":      "wedding",
	"personal trainer":     "personal-trainer",
	"fitness coach":        "personal-trainer",
	"trainer":              "personal-trainer",
	"real estate":          "realestate",
	"realtor":              "realestate",
	"real estate agent":    "realestate",
	"music teacher":        "music-teacher",
	"piano teacher":        "music-teacher",
	"guitar teacher":       "music-teacher",
	"voice teacher":        "music-teacher",
	"insurance agent":      "insurance-agent",
	"insurance":            "insurance-agent",
	"financial advisor":    "financial-advisor",
	"financial planner":    "financial-advisor",
	"architect":            "architect",
	"home inspector":       "home-inspector",
	"notary":               "notary",
	"notary public":        "notary",
	"immigration":          "immigration-consultant",
	"it consultant":        "it-consultant",
	"msp":                  "it-consultant",

	// Organizations
	"church":                "church",
	"parish":                "church",
	"congregation":          "church",
	"mosque":                "church",
	"synagogue":             "church",
	"temple":                "church",
	"nonprofit":             "nonprofit",
	"non-profit":            "nonprofit",
	"charity":               "nonprofit",
	"ngo":                   "nonprofit",
	"school":                "school",
	"teacher":               "school",
	"daycare":               "daycare",
	"childcare":             "daycare",
	"preschool":             "daycare",
	"hoa":                   "hoa",
	"homeowners association": "hoa",
	"condo association":      "hoa",
	"condo board":            "hoa",
	"makerspace":             "makerspace",
	"fab lab":                "makerspace",
	"hackerspace":            "makerspace",
	"gym":                    "gym",
	"fitness studio":         "gym",
	"crossfit":               "gym",
	"yoga studio":            "yoga-studio",
	"coworking":              "coworking",
	"coworking space":        "coworking",

	// Gaming
	"minecraft":        "minecraft",
	"minecraft server": "minecraft",
	"mc server":        "minecraft",
	"valheim":          "valheim",
	"valheim server":   "valheim",
	"plex":             "plex",
	"plex server":      "plex",
	"jellyfin":         "plex",
	"media server":     "plex",
	"game server":      "minecraft",
	"ark":              "ark-rust",
	"rust server":      "ark-rust",
	"fivem":            "fivem",
	"gta rp":           "fivem",
	"gmod":             "gmod",
	"garrys mod":       "gmod",
	"terraria":         "terraria",
	"csgo":             "csgo",
	"cs2":              "csgo",
	"counter strike":   "csgo",
	"foundry vtt":      "foundry-vtt",
	"foundry":          "foundry-vtt",
	"unraid":           "unraid",
	"truenas":          "truenas",
	"freenas":          "truenas",
	"proxmox":          "proxmox",
	"homelab":          "homelab",
	"home lab":         "homelab",
	"self hosted":      "homelab",

	// Content Creators
	"twitch":          "twitch",
	"streamer":        "twitch",
	"streaming":       "twitch",
	"youtuber":        "youtube",
	"youtube":         "youtube",
	"podcaster":       "podcast",
	"podcast":         "podcast",
	"newsletter":      "newsletter",
	"substack":        "newsletter",
	"band":            "band",
	"musician":        "band",
	"indie game dev":  "indie-gamedev",
	"game developer":  "indie-gamedev",
	"author":          "author",
	"writer":          "author",
	"self published":  "author",
	"graphic designer": "graphic-designer",
	"illustrator":      "illustrator",
	"comic artist":     "illustrator",
	"course creator":   "course-creator",
	"online course":    "course-creator",
	"video editor":     "video-editor",

	// Communities
	"book club":     "bookclub",
	"reading group": "bookclub",
	"dnd":           "tabletop",
	"d&d":           "tabletop",
	"tabletop":      "tabletop",
	"rpg group":     "tabletop",
	"pathfinder":    "tabletop",
	"scout troop":   "scouting",
	"boy scouts":    "scouting",
	"cub scouts":    "scouting",
	"girl scouts":   "scouting",
	"sports league": "sports-league",
	"rec league":    "sports-league",
	"running club":  "running-club",
	"cycling club":  "cycling-club",
	"hiking group":  "hiking-group",
	"car club":      "car-club",
	"car meet":      "car-club",

	// Hobbies
	"beekeeper":      "beekeeper",
	"beekeeping":     "beekeeper",
	"apiary":         "beekeeper",
	"homebrewer":     "homebrewer",
	"homebrew":       "homebrewer",
	"home brewing":   "homebrewer",
	"aquarium":       "aquarium",
	"reef tank":      "aquarium",
	"fish tank":      "aquarium",
	"3d printing":    "3d-printing",
	"3d printer":     "3d-printing",
	"woodworker":     "woodworker",
	"woodworking":    "woodworker",
	"woodshop":       "woodworker",
	"gardener":       "gardener",
	"garden":         "gardener",
	"gardening":      "gardener",
	"wine collector": "wine-collector",
	"wine cellar":    "wine-collector",
	"ham radio":      "ham-radio",
	"amateur radio":  "ham-radio",
	"board games":    "board-gamer",
	"board game":     "board-gamer",
	"astronomy":      "astronomy",
	"astronomy club": "astronomy",
	"telescope":      "astronomy",

	// Animals
	"dog breeder":      "dog-breeder",
	"puppy breeder":    "dog-breeder",
	"horse farm":       "horse-farm",
	"horse breeder":    "horse-farm",
	"equestrian":       "horse-farm",
	"cattle ranch":     "cattle-ranch",
	"ranch":            "cattle-ranch",
	"goat farm":        "goat-farm",
	"goats":            "goat-farm",
	"chickens":         "poultry-farm",
	"poultry":          "poultry-farm",
	"backyard chickens": "poultry-farm",

	// Education
	"homeschool":      "homeschool",
	"home school":     "homeschool",
	"language school": "language-school",
	"driving school":  "driving-school",
	"trade school":    "trade-school",

	// Property
	"airbnb":            "airbnb",
	"vacation rental":   "airbnb",
	"short term rental": "airbnb",
	"property manager":  "property-manager",
	"landlord":          "property-manager",
	"rental property":   "property-manager",
	"campground":        "campground",
	"rv park":           "campground",
	"storage facility":  "storage-facility",
	"self storage":      "storage-facility",

	// Misc
	"brewery":        "brewery",
	"winery":         "brewery",
	"distillery":     "brewery",
	"soap maker":     "soap-maker",
	"soap making":    "soap-maker",
	"candle maker":   "candle-maker",
	"candle making":  "candle-maker",
	"martial arts":   "martial-arts",
	"dojo":           "martial-arts",
	"karate":         "martial-arts",
	"bjj":            "martial-arts",
	"dance studio":   "dance-studio",
	"animal shelter": "animal-shelter",
	"rescue":         "animal-shelter",
	"food bank":      "food-bank",
	"food pantry":    "food-bank",
	"indie saas":     "indie-saas",
	"saas":           "indie-saas",
	"startup":        "indie-saas",
}

// QuickMatchLookup attempts to match normalized input to a pre-cached bundle.
// Returns bundle slug or empty string if no match.
func QuickMatchLookup(normalized string) string {
	// Exact match
	if slug, ok := quickMatch[normalized]; ok {
		return slug
	}

	// Try progressively shorter prefixes for compound inputs
	// "barber shop downtown" → "barber shop" → match
	words := strings.Fields(normalized)
	for i := len(words) - 1; i >= 1; i-- {
		prefix := strings.Join(words[:i], " ")
		if slug, ok := quickMatch[prefix]; ok {
			return slug
		}
	}

	// Try first word only
	// "therapist who specializes in trauma" → "therapist" → match
	if len(words) > 0 {
		if slug, ok := quickMatch[words[0]]; ok {
			return slug
		}
	}

	return "" // no match, proceed to Layer 2
}
