// Stockyard — "The complete LLM proxy toolkit."
package main

import "github.com/stockyard-dev/stockyard/internal/engine"

var (
	version = "dev"
	commit  = ""
	date    = ""
)

func main() {
	engine.Boot(engine.ProductConfig{
		Name:    "Stockyard",
		Product: "stockyard",
		Version: version,
		Features: engine.Features{
			SpendTracking:  true,
			SpendCaps:      true,
			Alerts:         true,
			Cache:          true,
			Validation:     true,
			Failover:       true,
			RateLimiting:   true,
			RequestLogging: true,
			FullBodyLog:    true,
			// Phase 1 expansion
			KeyPool:     true,
			PromptGuard: true,
			ModelSwitch: true,
			EvalGate:    true,
			UsagePulse:  true,
			// Phase 2 expansion
			PromptPad:   true,
			TokenTrim:   true,
			BatchQueue:  true,
			MultiCall:   true,
			StreamSnap:  true,
			LLMTap:      true,
			ContextPack: true,
			RetryPilot:  true,
			// Phase 3 expansion
			ToxicFilter:   true,
			ComplianceLog: true,
			SecretScan:    true,
			TraceLink:     true,
			IPFence:       true,
			EmbedCache:    true,
			AnthroFit:     true,
			AlertPulse:    true,
			ChatMem:       true,
			MockLLM:       true,
			TenantWall:    true,
			IdleKill:      true,
			// Phase 3 P2 expansion
			AgentGuard:    true,
			CodeFence:     true,
			HalluciCheck:  true,
			TierDrop:      true,
			DriftWatch:    true,
			FeedbackLoop:  true,
			ABRouter:      true,
			GuardRail:     true,
			GeminiShim:    true,
			LocalSync:     true,
			DevProxy:      true,
			PromptSlim:    true,
			PromptLint:    true,
			ApprovalGate:  true,
			OutputCap:     true,
			AgeGate:       true,
			VoiceBridge:   true,
			ImageProxy:    true,
			LangBridge:    true,
			ContextWindow: true,
			RegionRoute:   true,
			// Phase 3 P3 expansion
			ChainForge:    true,
			CronLLM:       true,
			WebhookRelay:  true,
			BillSync:      true,
			WhiteLabel:    true,
			TrainExport:   true,
			SynthGen:      true,
			DiffPrompt:    true,
			LLMBench:      true,
			MaskMode:      true,
			TokenMarket:   true,
			LLMSync:       true,
			ClusterMode:   true,
			EncryptVault:  true,
			MirrorTest:    true,
			// Phase 4 expansion
			ExtractML:      true,
			TableForge:     true,
			ToolRouter:     true,
			ToolShield:     true,
			ToolMock:       true,
			AuthGate:       true,
			ScopeGuard:     true,
			VisionProxy:    true,
			AudioProxy:     true,
			DocParse:       true,
			FrameGrab:      true,
			SessionStore:   true,
			ConvoFork:      true,
			SlotFill:       true,
			SemanticCache:  true,
			PartialCache:   true,
			StreamCache:    true,
			PromptChain:    true,
			PromptFuzz:     true,
			PromptMarket:   true,
			CostPredict:    true,
			CostMap:        true,
			SpotPrice:      true,
			LoadForge:      true,
			SnapshotTest:   true,
			ChaosLLM:       true,
			DataMap:        true,
			ConsentGate:    true,
			RetentionWipe:  true,
			PolicyEngine:   true,
			StreamSplit:    true,
			StreamThrottle: true,
			StreamTransform:true,
			ModelAlias:     true,
			ParamNorm:      true,
			QuotaSync:      true,
			ErrorNorm:      true,
			CohortTrack:    true,
			PromptRank:     true,
			AnomalyRadar:   true,
			EnvSync:        true,
			ProxyLog:       true,
			CliDash:        true,
			EmbedRouter:    true,
			FineTuneTrack:  true,
			AgentReplay:    true,
			SummarizeGate:  true,
			CodeLang:       true,
			PersonaSwitch:  true,
			WarmPool:       true,
			EdgeCache:      true,
			QueuePriority:  true,
			GeoPrice:       true,
			TokenAuction:   true,
			CanaryDeploy:   true,
			PlaybackStudio: true,
			WebhookForge:   true,
		},
	})
}
